// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("AddSubscription")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class AddSubscriptionFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "AddSubscription", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "AddSubscription.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User subscribes to a course and time")]
        public async System.Threading.Tasks.Task UserSubscribesToACourseAndTime()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User subscribes to a course and time", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Id",
                            "Name"});
                table1.AddRow(new string[] {
                            "1",
                            "Golf Course 1"});
                table1.AddRow(new string[] {
                            "2",
                            "Golf Course 2"});
#line 4
        await testRunner.GivenAsync("courses exist", ((string)(null)), table1, "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Email",
                            "CourseId",
                            "FromTime",
                            "ToTime",
                            "NumberOfPlayers"});
                table2.AddRow(new string[] {
                            "user@email.com",
                            "1",
                            "2025-01-01T09:00",
                            "2025-01-01T12:00",
                            "2"});
                table2.AddRow(new string[] {
                            "user@email.com",
                            "2",
                            "2025-02-01T09:00",
                            "2025-02-01T12:00",
                            "3"});
                table2.AddRow(new string[] {
                            "otherUser@email.com",
                            "2",
                            "2025-02-01T09:00",
                            "2025-02-01T12:00",
                            "3"});
#line 8
        await testRunner.GivenAsync("users subscribed to", ((string)(null)), table2, "Given ");
#line hidden
#line 13
        await testRunner.AndAsync("a user with email user@email.com wants to get subscriptions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
        await testRunner.WhenAsync("the request is made", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Email",
                            "CourseId",
                            "FromTime",
                            "ToTime",
                            "NumberOfPlayers"});
                table3.AddRow(new string[] {
                            "user@email.com",
                            "1",
                            "2025-01-01T09:00",
                            "2025-01-01T12:00",
                            "2"});
                table3.AddRow(new string[] {
                            "user@email.com",
                            "2",
                            "2025-02-01T09:00",
                            "2025-02-01T12:00",
                            "3"});
#line 15
        await testRunner.ThenAsync("the subscription are returned", ((string)(null)), table3, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User subscribes to an invalid course")]
        public async System.Threading.Tasks.Task UserSubscribesToAnInvalidCourse()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User subscribes to an invalid course", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Email",
                            "CourseId",
                            "FromTime",
                            "ToTime",
                            "NumberOfPlayers"});
                table4.AddRow(new string[] {
                            "user@email.com",
                            "3",
                            "2025-01-01T09:00",
                            "2025-01-01T12:00",
                            "2"});
#line 21
        await testRunner.GivenAsync("a user wants to subscribe to", ((string)(null)), table4, "Given ");
#line hidden
#line 24
        await testRunner.WhenAsync("the request is made", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "status",
                            "message"});
                table5.AddRow(new string[] {
                            "400",
                            "Course does not exist"});
#line 25
        await testRunner.ThenAsync("the request is not successful with", ((string)(null)), table5, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
