# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

schedules:
  - cron: "* 8-23 13-15 4 *"
    branches:
      include:
        - master
    displayName: Daily run at midnight
    always: true

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Sweetspot/Sweetspot.csproj'
    feedsToUse: 'select'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Sweetspot/Sweetspot.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    projects: 'Sweetspot/Sweetspot.csproj'