name: Run aengbot

on:
  schedule: 
    - cron: '*/7 6-22 * * *' # utc time zone on github runner
  workflow_dispatch:

jobs:
  RunAengbot:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up app
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 15
          max_attempts: 10
          command: |
            curl -H "XAPIKEY: ${{ secrets.AENGBOT_API_KEY }}" https://aenbot-api.azurewebsites.net/aengbot/wakeup 
            
      - name: Trigger scan
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 10
          max_attempts: 3
          command: |
            curl -H "XAPIKEY: ${{ secrets.AENGBOT_API_KEY }}" https://aenbot-api.azurewebsites.net/aengbot/trigger 
