name: Run aengbot

on:
  schedule: # utc time on github runner
    - cron: '*/7 6-22 * * *'
  workflow_dispatch:

jobs:
  RunAengbot:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up app
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 10
          max_attempts: 5
          command: |
            curl -H "XAPIKEY: ${{ secrets.AENGBOT_API_KEY }}" https://aenbot-api.azurewebsites.net/aengbot/wakeup 

      - name: Trigger scan
        uses: satak/webrequest-action@master
        with:
          url: 'https://aenbot-api.azurewebsites.net/aengbot/trigger'
          method: GET
          headers: '{"XAPIKEY": "${{ secrets.AENGBOT_API_KEY }}"}'