name: Run aengbot

on:
  schedule:
    - cron: "*/15 8-22 * * *"
  workflow_dispatch:    
      
jobs:
  RunAengbot:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up app
        uses: satak/webrequest-action@master
        with:
          url: 'https://aenbot-api.azurewebsites.net/aengbot/wakeUp'
          method: GET
          headers: '{"X_API_KEY": "${{ secrets.AENGBOT_API_KEY }}"}'
          
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
        
      - name: Wake up app
        uses: satak/webrequest-action@master
        with:
          url: 'https://aenbot-api.azurewebsites.net/aengbot/wakeUp'
          method: GET
          headers: '{"X_API_KEY": "${{ secrets.AENGBOT_API_KEY }}"}'
          
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Wake up app
        uses: satak/webrequest-action@master
        with:
          url: 'https://aenbot-api.azurewebsites.net/aengbot/trigger'
          method: GET
          headers: '{"X_API_KEY": "${{ secrets.AENGBOT_API_KEY }}"}'